import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';
import { Database } from '@/types/supabase';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabase = createClient<Database>(supabaseUrl, supabaseKey);

/**
 * Push Subscription API
 * 
 * This endpoint saves the user's browser subscription object to the database.
 * This object is generated by the browser's Push API and contains the endpoint URL and encryption keys.
 */
export async function POST(request: Request) {
    try {
        const { subscription, userId } = await request.json();

        if (!subscription || !userId) {
            return NextResponse.json({ error: 'Missing subscription or userId' }, { status: 400 });
        }

        // Upsert the subscription
        // We use 'upsert' to avoid duplicates if the same device subscribes twice.
        // The unique constraint is on (user_id, subscription).
        const { error } = await supabase
            .from('push_subscriptions')
            .upsert({
                user_id: userId,
                subscription: subscription
            }, { onConflict: 'user_id, subscription' });

        if (error) throw error;

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Error saving subscription:', error);
        return NextResponse.json({ error: 'Failed to save subscription' }, { status: 500 });
    }
}
